// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UcakBiletiRezervasyonSistemi.Data;

#nullable disable

namespace UcakBiletiRezervasyonSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108203404_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UcakBiletiRezervasyonSistemi.Models.Kullanici", b =>
                {
                    b.Property<string>("TcNo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TcNo");

                    b.ToTable("Kullanicilar");

                    b.HasDiscriminator().HasValue("Kullanici");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UcakBiletiRezervasyonSistemi.Models.Rezervasyon", b =>
                {
                    b.Property<string>("RezervasyonKodu")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RezervasyonKodu");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("AktifMi");

                    b.Property<string>("Mesaj")
                        .HasColumnType("longtext")
                        .HasColumnName("Mesaj");

                    b.Property<string>("MusteriTcNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("MusteriTcNo");

                    b.Property<DateTime>("RezervasyonTarihi")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RezervasyonTarihi");

                    b.Property<decimal>("ToplamFiyat")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("ToplamFiyat");

                    b.Property<string>("UcusNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("UcusNo");

                    b.HasKey("RezervasyonKodu");

                    b.ToTable("Rezervasyonlar", (string)null);
                });

            modelBuilder.Entity("UcakBiletiRezervasyonSistemi.Models.Ucus", b =>
                {
                    b.Property<string>("UcusNo")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UcusNo");

                    b.Property<int>("BosKoltukSayisi")
                        .HasColumnType("int")
                        .HasColumnName("BosKoltukSayisi");

                    b.Property<DateTime>("KalkisTarihiSaati")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("KalkisTarihiSaati");

                    b.Property<string>("KalkisYeri")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("KalkisYeri");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int")
                        .HasColumnName("Kapasite");

                    b.Property<decimal>("TemelFiyat")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("TemelFiyat");

                    b.Property<string>("VarisYeri")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("VarisYeri");

                    b.HasKey("UcusNo");

                    b.ToTable("Ucuslar", (string)null);
                });

            modelBuilder.Entity("UcakBiletiRezervasyonSistemi.Models.Yolcu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Ad");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Fiyat");

                    b.Property<string>("KoltukNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("KoltukNo");

                    b.Property<string>("KoltukTipi")
                        .HasColumnType("longtext")
                        .HasColumnName("KoltukTipi");

                    b.Property<string>("RezervasyonKodu")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RezervasyonKodu");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Soyad");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TcNo");

                    b.HasKey("Id");

                    b.HasIndex("RezervasyonKodu");

                    b.ToTable("Yolcular", (string)null);
                });

            modelBuilder.Entity("UcakBiletiRezervasyonSistemi.Models.Admin", b =>
                {
                    b.HasBaseType("UcakBiletiRezervasyonSistemi.Models.Kullanici");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("UcakBiletiRezervasyonSistemi.Models.Musteri", b =>
                {
                    b.HasBaseType("UcakBiletiRezervasyonSistemi.Models.Kullanici");

                    b.HasDiscriminator().HasValue("Musteri");
                });

            modelBuilder.Entity("UcakBiletiRezervasyonSistemi.Models.Yolcu", b =>
                {
                    b.HasOne("UcakBiletiRezervasyonSistemi.Models.Rezervasyon", null)
                        .WithMany("Yolcular")
                        .HasForeignKey("RezervasyonKodu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UcakBiletiRezervasyonSistemi.Models.Rezervasyon", b =>
                {
                    b.Navigation("Yolcular");
                });
#pragma warning restore 612, 618
        }
    }
}
